en:
  pages.404.title: "Page not found"
  pages.404.content: "We are sorry, but the page you requested cannot be found."
  pages.categories.title: "Course categories"
  pages.error.title: "Error"
  pages.error.content: "We're sorry, but something went wrong and the page cannot be displayed."
  pages.home.title: "Welcome to GetPly!"
  pages.home.intro: "Create and sell your own courses online.<br>Any language. Any level. Any topic.<br>We’re launching in 2017.<br>Request invitation-only early access now!"
  pages.select-language.choose: "Select your language"
  pages.select-language.login: "Login"
  pages.select-language.password: "Password"
  pages.select-language.sign-in: "Sign in"
  pages.select-language.or-sign-in: "Or sign in"
  partials.account.default.sign-in: "Sign in"
  partials.account.default.register: "Register"
  partials.account.register.email: "Enter email"
  partials.account.register.password: "Enter password"
  partials.account.signin.email: "Enter email"
  partials.account.signin.password: "Enter password"
  partials.account.signin.sign-in: "Sign in"
  partials.account.signin.sign-in-with: "or sign in with"
  partials.account.update.name: "Full name"
  partials.account.update.email: "New Email"
  partials.account.update.password: "New Password"
  partials.account.update.confirm: "Confirm password"
  partials.account.update.save: "Save changes"
  partials.site.header.courses: "Courses"
  partials.site.header.account: "Account"
  partials.site.header.logout: "Logout"
  partials.site.header.sign-up: "Sign up"
  partials.site.footer.help: "Help"
  partials.site.footer.terms: "Privacy & terms"
  components.categories.list.open-course: "Open courses"
  components.courseCreate.name: "Course name"
  components.courseCreate.category: "Select category"
  components.courses.empty: "There is no course data"
  components.courses.how-to-learn: "How do you want to study?"
  components.courses.flashcards: "Flash cards"
  components.courses.typed-input: "Typed input"
  components.courses.listen: "Listen"
  components.courseUpload.name: "Course name"
  components.courseUpload.category: "Category"
  components.courseUpload.only-zip: "only ZIP files allowed"
  components.courseUpload.created: "was created"
  components.courseUpload.create: "Create a course"
  components.units.empty: "There is no unit data"
  components.units.open: "Open unit"
  components.units.start: "Start learning"
  components.units.how-to-learn: "Как вы хотите учиться?"
  components.units.begin: "Начать"
  components.units.cancel: "Отмена"
  components.units.flashcards: "Flash cards"
  components.units.typed-input: "Typed input"
  components.units.listen: "Listen"
  components.userCourses.empty: "You have no courses."
ru:
  pages.404.title: "Страница не найдена"
  pages.404.content: "Мы сожалеем, но запрашиваемая страница не найдена."
  pages.categories.title: "Выберите категорию"
  pages.error.title: "Ошибка"
  pages.error.content: "Что-то пошло не так и страница не может быть отображена."
  pages.home.title: "Добро пожаловать в GetPly!"
  pages.home.intro: "Создавайте и продавайте ваши собственные курсы онлайн.<br>На любых языках. Любого уровня сложности. На любые темы.<br>Мы запускаемся в 2017.<br>Зарегистрируйтесь для участия в программе раннего доступа!"
  pages.select-language.choose: "Выберите ваш язык"
  pages.select-language.login: "Логин"
  pages.select-language.password: "Пароль"
  pages.select-language.sign-in: "Войти"
  pages.select-language.or-sign-in: "Или войдите"
  partials.account.default.sign-in: "Войти"
  partials.account.default.register: "Зарегистрироваться"
  partials.account.register.email: "Введите email"
  partials.account.register.password: "Введите пароль"
  partials.account.signin.email: "Введите email"
  partials.account.signin.password: "Введите пароль"
  partials.account.signin.sign-in: "Войти"
  partials.account.signin.sign-in-with: "или войдите с помощью"
  partials.account.update.name: "Полное имя"
  partials.account.update.email: "Новый e-mail"
  partials.account.update.password: "Новый пароль"
  partials.account.update.confirm: "Подтвердите пароль"
  partials.account.update.save: "Сохранить изменения"
  partials.site.header.courses: "Курсы"
  partials.site.header.account: "Профиль"
  partials.site.header.logout: "Выйти"
  partials.site.header.sign-up: "Зарегистрироваться"
  partials.site.footer.help: "Помощь"
  partials.site.footer.terms: "Приватность и условия"
  components.categories.list.open-course: "Открыть курсы"
  components.courseCreate.name: "Название курса"
  components.courseCreate.category: "Выберите категорию"
  components.courses.empty: "Курс пустой"
  components.courses.how-to-learn: "Как вы хотите проходить урок?"
  components.courses.flashcards: "Флеш-карточки"
  components.courses.typed-input: "Печатный ввод"
  components.courses.listen: "Слушать"
  components.courseUpload.name: "Название курса"
  components.courseUpload.category: "Категория"
  components.courseUpload.only-zip: "только ZIP файлы разрешены к загрузке"
  components.courseUpload.created: "был создан"
  components.courseUpload.create: "Создать курс"
  components.units.empty: "Юнит не содержит карточек"
  components.units.open: "Открыть юнит"
  components.units.start: "Начать"
  components.units.how-to-learn: "Как вы хотите учиться?"
  components.units.begin: "Начать"
  components.units.cancel: "Отмена"
  components.units.flashcards: "Флеш-карточки"
  components.units.typed-input: "Печатный ввод"
  components.units.listen: "Слушать"
  components.userCourses.empty: "У вас еще нет собственных курсов."
